language: ruby
rvm:
  - 2.1.5
# command to install dependencies
# added ruby test
script: ruby test/test_pga_leaderboard.rb
notifications:
    travis encrypt "nonamed-hq:x23cfOE12hD5Q0dCJDGpaMyw" --add notifications.slack
